### ISSUE TITLE
Traps are always logged into Application event log

### ISSUE THREAD

**Issue by JDA88** [AlexB7/snmptt#1]
**Used version:** 1.5 in Windows
**Expected behavior:** `eventlog_enable` is at 0 so I expected the traps to not be logged into the Application event log

**Behavior:** I don’t seen any difference in trap login no matter the value of `eventlog_enable`

Am i missing something? The doc state : "_# Set to 1 to enable logging of *TRAPS* to the event log._"

**Comment by AlexB7** [comment]
This has been fixed for 1.5.1.

Can you please re-create your issues (including this one) at https://github.com/snmptt?

**Comment by JDA88** [comment]
Great! Sorry I used the wrong repo, I'll recreate everything ASAP
